object frm_actorscript: Tfrm_actorscript
  Left = 251
  Top = 122
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  Caption = 'Actor Script'
  ClientHeight = 472
  ClientWidth = 652
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Label4: TLabel
    Left = 8
    Top = 6
    Width = 50
    Height = 13
    Caption = 'Life Script:'
  end
  object Label2: TLabel
    Left = 416
    Top = 6
    Width = 60
    Height = 13
    Caption = 'Move Script:'
  end
  object BitBtn1: TBitBtn
    Left = 616
    Top = 2
    Width = 22
    Height = 22
    Hint = 'Undo'
    TabOrder = 1
    OnClick = BitBtn1Click
    Glyph.Data = {
      36030000424D3603000000000000360000002800000010000000100000000100
      18000000000000030000120B0000120B00000000000000000000FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8400
      00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF840000840000840000840000840000FF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF840000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      840000840000840000840000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FF840000FFFFFFFFFFFFFFFFFFFFFFFF840000840000840000FFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF840000FFFFFFFFFFFFFFFFFFFFFFFF
      840000840000FFFFFF840000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FF840000FFFFFFFFFFFFFFFFFFFFFFFF840000FFFFFFFFFFFFFFFFFF84000084
      0000FFFFFFFFFFFFFFFFFFFFFFFF840000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF840000840000840000840000FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  end
  object BitBtn2: TBitBtn
    Left = 384
    Top = 2
    Width = 22
    Height = 22
    Hint = 'Undo'
    TabOrder = 2
    OnClick = BitBtn2Click
    Glyph.Data = {
      36030000424D3603000000000000360000002800000010000000100000000100
      18000000000000030000120B0000120B00000000000000000000FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8400
      00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF840000840000840000840000840000FF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF840000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      840000840000840000840000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FF840000FFFFFFFFFFFFFFFFFFFFFFFF840000840000840000FFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF840000FFFFFFFFFFFFFFFFFFFFFFFF
      840000840000FFFFFF840000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FF840000FFFFFFFFFFFFFFFFFFFFFFFF840000FFFFFFFFFFFFFFFFFF84000084
      0000FFFFFFFFFFFFFFFFFFFFFFFF840000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF840000840000840000840000FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  end
  object cb_lifeWW: TCheckBox
    Left = 280
    Top = 4
    Width = 97
    Height = 17
    Caption = 'Word Wrap'
    TabOrder = 3
    OnClick = cb_lifeWWClick
  end
  object cb_moveWW: TCheckBox
    Left = 512
    Top = 4
    Width = 97
    Height = 17
    Caption = 'Word Wrap'
    TabOrder = 4
    OnClick = cb_moveWWClick
  end
  object BitBtn3: TBitBtn
    Left = 520
    Top = 424
    Width = 121
    Height = 25
    Caption = '&Apply Changes'
    TabOrder = 5
    OnClick = BitBtn3Click
    Kind = bkYes
  end
  object re_movescript: TRichEdit
    Left = 416
    Top = 26
    Width = 225
    Height = 391
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Courier New'
    Font.Style = []
    HideSelection = False
    ParentFont = False
    ScrollBars = ssBoth
    TabOrder = 0
    WordWrap = False
    OnKeyPress = re_movescriptKeyPress
    OnSelectionChange = re_movescriptSelectionChange
  end
  object Button1: TButton
    Left = 8
    Top = 424
    Width = 145
    Height = 25
    Caption = 'Game Descriptions Values'
    TabOrder = 6
    OnClick = Button1Click
  end
  object re_lifescript: TRichEdit
    Left = 8
    Top = 26
    Width = 401
    Height = 391
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Courier New'
    Font.Style = []
    HideSelection = False
    ParentFont = False
    ScrollBars = ssBoth
    TabOrder = 7
    WordWrap = False
    OnKeyPress = re_lifescriptKeyPress
    OnSelectionChange = re_lifescriptSelectionChange
  end
  object status_script: TStatusBar
    Left = 0
    Top = 453
    Width = 652
    Height = 19
    Panels = <
      item
        Text = '0: 0'
        Width = 70
      end
      item
        Width = 350
      end
      item
        Text = '0: 0'
        Width = 70
      end
      item
        Width = 50
      end>
    SimplePanel = False
  end
  object LifeSyntax: TColorSyntax
    About = 'TColorSyntax'
    Control = re_lifescript
    Layers.Strings = (
      
        '  10  7clGreen 11Courier New  210  10  10  10  10  213  10 15DEF' +
        'AULT_CHARSET'
      
        '  11  5clRed 11Courier New  210  10  10  10  10  213  10 15DEFAU' +
        'LT_CHARSET'
      
        '  12  9clFuchsia 11Courier New  210  10  10  10  10  213  10 15D' +
        'EFAULT_CHARSET'
      
        '  13  6clBlue 11Courier New  210  10  10  10  10  213  10 15DEFA' +
        'ULT_CHARSET'
      
        '  14  8clMaroon 11Courier New  210  10  10  10  10  213  10 15DE' +
        'FAULT_CHARSET'
      
        '  15  8clMaroon 11Courier New  210  10  10  10  10  213  10 15DE' +
        'FAULT_CHARSET'
      
        '  18  6clTeal 11Courier New  210  10  10  10  10  213  10 15DEFA' +
        'ULT_CHARSET'
      
        '  16  6clBlue 11Courier New  210  10  10  10  10  213  10 15DEFA' +
        'ULT_CHARSET')
    OnlyChangedText = True
    Parser = LifeParser
    Left = 304
    Top = 424
  end
  object LifeParser: TParserAll
    About = 'TParserAll'
    BNF.Strings = (
      '<comportament> ::= COMPORTEMENT|END_COMPORTEMENT|END'
      '<conditions> ::= IF|ONEIF|NEVERIF|OR_IF|NO_IF|SWIF|ELSE|ENDIF'
      
        '<condvars> ::= COL_OBJ|DISTANCE|ZONE_OBJ|BODY_OBJ|ANIM_OBJ|COL|Z' +
        'ONE|BODY|L_TRACK_OBJ|ANIM|L_TRACK|FLAG_CUBE|CONE_VIEW|HIT_BY|ACT' +
        'ION|LIFE_POINT_OBJ|FLAG_GAME|LIFE_POINT|NUM_LITTLE_KEYS|NUM_GOLD' +
        '_PIECES|COMPORTEMENT_HERO|CHAPTER|DISTANCE_3D|USE_INVENTORY|CHOI' +
        'CE|FUEL|CARRY_BY|CDROM'
      '<behavior> ::= NORMAL|ATHLETIC|AGRESSIVE|DISCRETE'
      '<digD> ::= '#39'0'#39'..'#39'9'#39
      '<numD> ::= <digD><numD>|<digD>'
      
        '<macros> ::= NOP|follow|OFFSET|LABEL|RETURN|SET_LIFE_OBJ|SET_TRA' +
        'CK_OBJ|SET_LIFE|SET_TRACK|MESSAGE|SET_DIR_OBJ|FALLABLE|SET_DIR|C' +
        'AM_FOLLOW|SET_COMPORTEMENT_OBJ|SET_FLAG_CUBE|SET_COMPORTEMENT|SE' +
        'T_FLAG_GAME|KILL_OBJ|SUICIDE|USE_ONE_LITTLE_KEY|GIVE_GOLD_PIECES' +
        '|END_LIFE|STOP_L_TRACK|RESTORE_L_TRACK|MESSAGE_OBJ|INC_CHAPTER|F' +
        'OUND_OBJECT|SET_DOOR_LEFT|SET_DOOR_RIGHT|SET_DOOR_UP|SET_DOOR_DO' +
        'WN|GIVE_BONUS|CHANGE_CUBE|OBJ_COL|BRICK_COL|INVISIBLE|ZOOM|POS_P' +
        'OINT|SET_MAGIC_LEVEL|SUB_MAGIC_POINT|SET_LIFE_POINT_OBJ|SUB_LIFE' +
        '_POINT_OBJ|HIT_OBJ|PLAY_FLA|PLAY_MIDI|INC_CLOVER_BOX|SET_USED_IN' +
        'VENTORY|ADD_CHOICE|ASK_CHOICE|BIG_MESSAGE|INIT_PINGOUIN|SET_HOLO' +
        '_POS|CLR_HOLO_POS|ADD_FUEL|SUB_FUEL|SET_GRM|SAY_MESSAGE|SAY_MESS' +
        'AGE_OBJ|FULL_POINT|BETA|GRM_OFF|FADE_PAL_RED|FADE_ALARM_RED|FADE' +
        '_ALARM_PAL|FADE_RED_PAL|FADE_RED_ALARM|FADE_PAL_ALARM|EXPLODE_OB' +
        'J|BULLE_ON|BULLE_OFF|ASK_CHOICE_OBJ|SET_DARK_PAL|SET_NORMAL_PAL|' +
        'MESSAGE_SENDELL|ANIM_SET|HOLOMAP_TRAJ|GAME_OVER|THE_END|MIDI_OFF' +
        '|PLAY_CD_TRACK|PROJ_ISO|PROJ_3D|TEXT|CLEAR_TEXT|BRUTAL_EXIT'
      '<tab> ::= #009'
      '<CR> ::= #013#010'
      '<comment> ::= REM<body>'
      '<body> ::= <CR>|#032..#255<body>|<tab><body>|'#39#39)
    CaseSensitive = True
    Left = 336
    Top = 424
  end
  object TrackSyntax: TColorSyntax
    About = 'TColorSyntax'
    Control = re_movescript
    Layers.Strings = (
      
        '  10  7clGreen 11Courier New  210  10  10  10  10  213  10 15DEF' +
        'AULT_CHARSET'
      
        '  11  5clRed 11Courier New  210  10  10  10  10  213  10 15DEFAU' +
        'LT_CHARSET'
      
        '  12  6clBlue 11Courier New  210  10  10  10  10  213  10 15DEFA' +
        'ULT_CHARSET'
      
        '  13  8clMaroon 11Courier New  210  10  10  10  10  213  10 15DE' +
        'FAULT_CHARSET'
      
        '  14  8clMaroon 11Courier New  210  10  10  10  10  213  10 15DE' +
        'FAULT_CHARSET'
      
        '  17  6clTeal 11Courier New  210  10  10  10  10  213  10 15DEFA' +
        'ULT_CHARSET')
    OnlyChangedText = True
    Parser = TrackParser
    Left = 440
    Top = 424
  end
  object TrackParser: TParserAll
    About = 'TParserAll'
    BNF.Strings = (
      '<labels> ::= END|LABEL'
      '<labels2> ::= STOP'
      
        '<trackmacros> ::= BODY|ANIM|GOTO_POINT|WAIT_ANIM|LOOP|ANGLE|POS_' +
        'POINT|GOTO_SYM_POINT|WAIT_NUM_ANIM|GOTO|SAMPLE|GOTO_POINT_3D|SPE' +
        'ED|BACKGROUND|WAIT_NUM_SECOND|NO_BODY|BETA|OPEN_LEFT|OPEN_RIGHT|' +
        'OPEN_UP|OPEN_DOWN|CLOSE|SAMPLE_ALWAYS|WAIT_DOOR|SAMPLE_RND|SAMPL' +
        'E_STOP|PLAY_FLA|REPEAT_SAMPLE|SIMPLE_SAMPLE|FACE_TWINKEL|ANGLE_R' +
        'ND'
      '<digD> ::= '#39'0'#39'..'#39'9'#39
      '<numD> ::= <digD><numD>|<digD>'
      '<tab> ::= #009'
      '<CR> ::= #013#010'
      '<comment> ::= REM<body>'
      '<body> ::= <CR>|#032..#255<body>|<tab><body>|'#39#39)
    CaseSensitive = False
    Left = 472
    Top = 424
  end
end
